# Generated by Django 3.2.19 on 2023-06-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='amount_due',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='previous_jobs_count',
            field=models.IntegerField(),
        ),
    ]
