name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    # if: ${{ false }}
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: COPY FILES TO SERVER
        uses: appleboy/scp-action@master
        with:
          host: 167.71.32.138
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "."
          target: "~/aktos"

      - name: BUILD APP AND RUN IN SERVER
        uses: appleboy/ssh-action@master
        with:
          host: 167.71.32.138
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd aktos
            mv Caddyfile_prod Caddyfile
            make build
